# Generated by Django 4.2.3 on 2023-07-26 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customuser_full_name_customuser_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(4, message='Full name must be at least 4 characters long.'), django.core.validators.MaxLengthValidator(100, message='Full name cannot exceed 100 characters.'), django.core.validators.RegexValidator(code='invalid_full_name', message='Full name must contain only alphabets and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
    ]
