# Generated by Django 4.2.3 on 2023-07-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
