# Generated by Django 4.2.3 on 2023-08-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_name_topic_title_remove_subject_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
