# Generated by Django 3.2.3 on 2023-08-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_customuser_about_alter_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
    ]
