# Generated by Django 3.2.3 on 2023-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
