# Generated by Django 3.2.3 on 2024-01-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
